CREATE OR REPLACE TYPE TP_PRODUCTO AS OBJECT (
    ID_PRODUCTO     NUMBER(6),
    ID_MARCA        NUMBER(6),
    NOMBRE          VARCHAR2(30),
    STOCK           NUMBER(3),
    VALOR_UNITARIO  NUMBER(6),
    FECHA_VENC      DATE,
    IVA             NUMBER(2),
    ACTIVO          NUMBER(1), 
    JSON_DATA       CLOB       
);
/

CREATE TYPE TBL_PRODUCTOS IS TABLE OF TP_PRODUCTO;
/

CREATE OR REPLACE TYPE TP_PROVEEDOR AS OBJECT (
    CODIGO      NUMBER(6),
    NOMBRE      VARCHAR2(20),
    TELEFONO    NUMBER(6),
    ACTIVO      NUMBER(1),
    JSON_DATA   CLOB
);
/

CREATE TYPE TBL_PROVEEDORES IS TABLE OF TP_PROVEEDOR;
/

CREATE OR REPLACE TYPE TP_DIRECTORIO AS OBJECT (
    ID_PRODUCTO     NUMBER(6),
    CODIGO          NUMBER(6),
    ACTIVO          NUMBER(1),
    JSON_DATA       CLOB
);
/

CREATE TYPE TBL_DIRECTORIOS IS TABLE OF TP_DIRECTORIO;
/