version: '3.9'

services:
  oracledb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oracledb
    ports:
      - "${ORACLE_PORT:-1522}:1521"
      - "${ORACLE_EM_PORT:-8080}:8080"
    environment:
      ORACLE_PWD: oracle
      ORACLE_DATABASE: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./db_scripts/scripts:/opt/oracle/scripts/manual/scripts
      - ./db_scripts/packages:/opt/oracle/scripts/manual/packages
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -s /nolog <<< 'connect sys/oracle@oracledb:1521/XEPDB1 as sysdba; SELECT 1 FROM DUAL; exit;' | grep -q '1' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10m
    networks:
      - almacen_network

  flask-web:
    build:
      context: ./flask-web
      dockerfile: Dockerfile
    container_name: flask-web
    ports:
      - "5000:5000"
    depends_on:
      oracledb:
        condition: service_healthy
    environment:
      ORACLE_HOST: oracledb
      ORACLE_PORT: 1521
      ORACLE_USER: laura
      ORACLE_PASSWORD: Laura2004
      ORACLE_DATABASE: XEPDB1
    networks:
      - almacen_network

networks:
  almacen_network:
    driver: bridge

volumes:
  oracle_data:
    driver: local
  