services:
  oracledb:
    build:
      context: . 
      dockerfile: Dockerfile
      args: 
        APP_USER: laura
        APP_USER_PWD: Laura2004
        ORACLE_PWD: oracle

    container_name: oracledb
    ports:
      - "${ORACLE_PORT:-1522}:1521" 
      - "${ORACLE_EM_PORT:-8080}:8080" 
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
      - APP_USER=${APP_USER}
      - APP_USER_PWD=${APP_USER_PWD}
      - ORACLE_DATABASE=${ORACLE_DATABASE}
      # Variables adicionales necesarias para Oracle XE
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./db_scripts:/opt/oracle/scripts/manual
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -s /nolog <<< 'connect sys/oracle@localhost:1521/XE as sysdba; SELECT 1 FROM DUAL; exit;' | grep -q '1' && echo 'OK' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10m

volumes:
  oracle_data:
    driver: local