version: '3.8'

services:
  oracledb:
    build:
      context: . 
      dockerfile: Dockerfile
      args: 
        APP_USER: laura
        APP_USER_PWD: Laura2004
        ORACLE_PWD: oracle

    container_name: oracledb
    ports:
      - "1522:1521" 
      - "8080:8080" 
    environment:

      - ORACLE_PWD=${ORACLE_PWD:-oracle}
      - APP_USER=${APP_USER:-laura}
      - APP_USER_PWD=${APP_USER_PWD:-Laura2004}
    volumes:

      - ./db_scripts/03_initial_data.sql:/opt/oracle/scripts/startup/03_initial_data.sql
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "ls /opt/oracle/oradata/XE/pdbseed/system01.dbf"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  oracle_data:
    driver: local