CREATE USER laura IDENTIFIED BY Laura2004;

GRANT CONNECT TO laura;
GRANT RESOURCE TO laura;
GRANT CREATE SESSION TO laura;
GRANT UNLIMITED TABLESPACE TO laura;
GRANT RESTRICTED SESSION TO laura;
EXIT;