-- insert de la tabla empleados
-- creado por:Jose camilo molina
-- fecha creacion: 02/09/2014

-- modificado por:

-- fecha modificacion:

-- descripcion:


INSERT INTO empleados VALUES(1,'PEDRO', 'CARDENAS','PEDRO@HOTMAIL.COM','M',NULL,117);
INSERT INTO empleados VALUES(2,'FELIPE', 'GUTIERREZ','FELIPE@YAHOO.COM','M',1,112);
INSERT INTO empleados VALUES(3,'ANGELA', 'LOPEZ','ANGELA@GMAIL.COM','F',1,104);
INSERT INTO empleados VALUES(4,'DIEGO', 'HERNANDEZ','DIEGO@HOTMAIL.COM','M',2,102);
INSERT INTO empleados VALUES(5,'YESICA', 'RODRIGUEZ','YESIK@GMAIL.COM','F',2,107);
INSERT INTO empleados VALUES(6,'JAVIER', 'PEREZ','PEREZ@YAHOO.COM','M',3,110);
INSERT INTO empleados VALUES(7,'JOSE', 'PACHECO','JOSE@YAHOO.ES','M',3,111);
INSERT INTO empleados VALUES(8,'CRISTIAN', 'SAMACA','CRISTIAN@HOTMAIL.COM','M',5,106);
INSERT INTO empleados VALUES(9,'YINETH', 'SALAZAR','YINETH@GMAIL.COM','F',4,107);
INSERT INTO empleados VALUES(10,'FANY', 'AYALA','FANY.AYALA@GMAIL.COM','F',4,103);
INSERT INTO empleados VALUES(11,'LUCAS', 'REYES','LUCAS21@HOTMAIL.COM','M',6,108);   