INSERT INTO marcas VALUES(90,'PIRELLI');
INSERT INTO marcas VALUES(91,'LAND CRUISER');
INSERT INTO marcas VALUES(92,'VACKORT');
INSERT INTO marcas VALUES(93,'WILLARD');
INSERT INTO marcas VALUES(94,'ILLUX TRUCK');
